### ISSUE TITLE
Can't Open anything whit .js

### ISSUE THREAD

**Issue by Dr4l** [Baterka/SteamSetsBot#1]
So i installed node.js but every time I try to open the file it says that It found an unexpected ;
I changed to Notepad++ but then I couldn't install or run the program
Please help

**Comment by Baterka** [comment]
Hi,
This project is unmaintained and I am not giving free support for it.
If you don't have skill to set it up, then learn how to do it or pay me and I will set it up for you. You can contact me on Steam: https://steamcommunity.com/id/czbaterka
